spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/registry?useTimezone=true&serverTimezone=UTC"
    username: "root"
    password: "localhost"
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
